services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      # PNPM_HOME: /pnpm
      MONGODB_URI: mongodb://mongo:27017/CMDB
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/mobile/node_modules
      - /app/packages/shared-utils/node_modules
      - /app/packages/tsconfig/node_modules
      - pnpm-store:/pnpm/store

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
   pnpm-store:
   mongo-data: