services:
  minio:
    image: minio/minio
    restart: always
    command: [ "server", "--console-address", ":9001", "/data" ]
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioSecret
    volumes:
      - minio-data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set minioDocker http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};
      /usr/bin/mc mb minioDocker/${MINIO_BUCKET};
      /usr/bin/mc anonymous set download minioDocker/${MINIO_BUCKET};
      exit 0;
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-api
    container_name: api
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      # PNPM_HOME: /pnpm
      MONGODB_URI: mongodb://mongo:27017/CMDB
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CI: true
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/enricher/node_modules
      - /app/apps/mobile/node_modules
      - /app/apps/aiworker/node_modules
      - /app/packages/shared-utils/node_modules
      - /app/packages/tsconfig/node_modules
      - pnpm-store:/pnpm/store

  enricher:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-enricher
    container_name: enricher
    env_file:
      - .env
    environment:
      # PNPM_HOME: /pnpm
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/enricher/node_modules
      - /app/apps/mobile/node_modules
      - /app/apps/aiworker/node_modules
      - /app/packages/shared-utils/node_modules
      - /app/packages/tsconfig/node_modules
      - pnpm-store:/pnpm/store

  aiworker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev-aiworker
    container_name: aiworker
    env_file:
      - .env
    environment:
      # PNPM_HOME: /pnpm
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
      - /app/apps/enricher/node_modules
      - /app/apps/mobile/node_modules
      - /app/apps/aiworker/node_modules
      - /app/packages/shared-utils/node_modules
      - /app/packages/tsconfig/node_modules
      - pnpm-store:/pnpm/store

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  nats:
    image: nats:2-alpine
    restart: always
    ports:
      - "4222:4222"

volumes:
   pnpm-store:
   mongo-data:
   minio-data: