services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cook-me-api:latest
    container_name: api
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongo:27017/CMDB
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data: